#[dist]
#functions = './functions'
#
#[[redirects]]
#from = "/jobs"
#to = "/.netlify/functions/jobs"
#status = 200
#
#[[redirects]]
#from = "/degrees"
#to = "/.netlify/functions/jobs"
#status = 200
#
#[[redirects]]
#from = "/spotlights"
#to = "/.netlify/functions/jobs"
#status = 200
